version: '3.9'

services:
    postgres:
        image: postgres:16
        container_name: jewelnotes-db
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: jnl_core_dev
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
            - ./db/init:/docker-entrypoint-initdb.d
        restart: unless-stopped
volumes:
    pgdata:
